[package]
name = "pwdcp"
version = "0.1.0"
authors = ["corytodd"]

[dependencies]
clipboard = "0.5.0"


[target.'cfg(all(unix, not(any(target_os="macos", target_os="android", target_os="emscripten"))))'.dependencies]
x11-clipboard = "0.6.1"